name             'elastichef'
maintainer       'Innovisors'
maintainer_email 'john.casey@innovisors.com'
license          'MIT'
description      'Installs/Configures elastichef'
long_description 'Installs/Configures elastichef'
version          '0.1.0'
